spring.application.name=shopwave

spring.datasource.url=jdbc:postgresql://localhost:5433/shopwave
spring.datasource.username=shopwave
spring.datasource.password=shopwave123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8081

jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e4ac0f56a7d2e7bf5c5b3d1f2
jwt.expiration=86400000